### ISSUE TITLE
Remove module when all elements are removed

### ISSUE THREAD

**Issue by raffazizzi** [raffazizzi/romajs#1]
If a user removes all elements belonging to a module, the module should be removed as well.

**Comment by jamescummings** [comment]
Are they still able to add back new elements to that module (or do new elements have to be added either sans module or to a new module)?

**Comment by raffazizzi** [comment]
@jamescummings if by "new elements" you mean selecting a module's element and not creating an entirely new element for a module, then yes. The current behavior is: when a new element from an unselected module is added, it will be added as `<moduleRef key="module" include="element"/>`.

**Comment by jamescummings** [comment]
Ah. No. I meant that I include a module, delete all its elements,  then add an entirely new element in a different namespace but want to put it in that module.  (This is frivolous of course, I don't even know if that is conformant.)

**Comment by raffazizzi** [comment]
I haven't tackled element creation yet 😀

**Comment by jamescummings** [comment]
Fair enough.  :-)
